language: node_js

node_js:
  - "0.12"

sudo: required

services:
  - docker

before_script:
  - npm install -g gulp

script: gulp

after_success:
  - docker build -t renatn/tol-material .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push renatn/tol-material:latest